project:
  type: book

book:
  title: "Are current sortition methods creating representative panels? A framework analysis"
  author: "Daniel Loza"
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "02-chap2.qmd"
    - "03-chap3.qmd"
    - "04-chap4.qmd"
    - "refs.qmd"
  sidebar:
    style: "docked"

bibliography: thesisrefs.bib
csl: american-statistical-association.csl
degreetype: Bachelor of Commerce (Honours)
submitted: 2026
affiliation: Department of Econometrics & Business Statistics
degrees: 'B.Bus., Monash University'

format:
  monashthesis-html: default
  monashthesis-pdf: default
