\pagenumbering{arabic}\setcounter{page}{1}
# Introduction {#sec-intro}

```{r}
#| label: load_packages
#| include: false
library(dplyr)
library(ggplot2)
library(readr)
library(tidyr)
library(tsibble)
library(feasts)
library(fable)
library(UpSetR)
library(here)
library(tidyverse)
```

## Topic

This thesis aims to evaluate whether current sortition methods and ideologies lead to actually representative panels in practice. Through simulation and visualisation of algorithm performance, we will examine whether current tools are producing panels that are representative.

## Background and Motivation

In a social landscape where the public is growing progressively disillusioned with its representation in politics [@landemoreOpinionNoShy2026], it is important to consider ways in which we can foster more inclusive decision-making practices. One way of achieving this, adopted recently by an increasing number of institutions, including the Parisian [@ParisCreatesPermanent], Irish [@walshDissatisfiedEngagedCitizen2021], and British Columbian [@wardExperimentPoliticalCommunication2008] governments, is using sortition to create panels that are more representative of the population for political discussions and deliberations. As a result, the need for fair and representative methods of building panels is only growing, and progress is being made in the structure of selective algorithms. However, there are still many challenges to overcome in order to ensure that these panels consistently achieve the level of representation that they set out to.

Sortition is a method of selection that uses random sampling to create panels that should be descriptively representative of a population. It has been used in various contexts, reaching as far back as ancient Athens, where it was how jurors were selected, and into modern times for citizens' assemblies, as mentioned earlier. The idea is that by randomly selecting individuals from the population, we can create panels that are more representative and inclusive than those selected through traditional methods. Sortition also reduces dominance by elites or highly engaged groups, enabling broader participation across social classes [@Giuliani2025SortitionIP], making it more likely that decisions are in the relevant population's best interest.

According to @Flanigan2021FairAF, sortition creates groups that are statistical “mini-publics” of society, reflecting demographics and perspectives more accurately than elected bodies. These sorts of panels enable more inclusive and representative decision-making processes, which can lead to better outcomes and increased public trust and engagement. They also encourage more diverse perspectives and can help to break down barriers between different groups in society, fostering greater understanding and collaboration.

One of the main roadblocks in sortition is ensuring that the selection process is transparent and fair, and that the panels are truly representative of the population in terms of demographics and perspectives. But this raises the questions of what it means to be fair, what it means to be representative, and how these look from a systematic perspective.

Sortition methods have been evolving over time. Prior to algorithmic means, panel selection was carried out through simple self-selection (response to survey/advertising) and proportional sampling to meet panel size requirements. As sortition began to grow more robust, the Legacy [@Flanigan2021FairAF] techniques started surfacing--these saw panels put together through simple choosing of respondents who met the most required "category" condition at any given moment, and would continue iterating until the required marginal counts were present in the selected panel. This led to situations of extreme selection likelihoods, if minorities existed--as members were selected indiscriminately of implied likelihood, meaning there were situations where an individual would potentially be selected 0% of the time. To counteract this, the more systematic algorithm "MaxiMin" was developed [@baharavFairManipulationRobustTransparent2024]; seeking not only to meet panel quotas, but to raise the lowest individual's selection likelihood, to eliminate the 0% selection case, in order to improve representativeness. This, however, now presented the risk of likelihood manipulation, as selection was based more directly on selection as a combination of all category responses given by an individual, rather than pure counts needed for the panel to be filled. As a result, the inverse function "MiniMax" was employed to reduce extreme cases on the other end--eliminating the 100% selection chance case by minimising maximal selection likelihood of any given individual, providing an approach that was more resistant and robust to coercion, but simultaneously reintroducing the potential 0% likelihood problem. Though robustness itself lies beyond the scope of this paper's aims, it is important to note the existence of MiniMax as an approach to the sortition problem, as it impacted further algorithmic development, and robustness as a goal presents an opportunity for further investigation.

More recently, and of direct relevance to the current study, further iterations of MiniMax and MaxiMin, in the forms of "LexiMin" [@Flanigan2021FairAF] and "Goldilocks" [@baharavFairManipulationRobustTransparent2024], were established. These present more generally practical outcomes, with the former being used in industry at present. LexiMin takes the idea of MaxiMin and repeats it for every individual sequentially, maximising _all_ individuals' likelihoods, rather than just those who sit at the absolute bottom. Thus, raising the selection likelihood floor for the participant pool overall. It is, however, like MaxiMin, vulnerable to manipulation (which remains beyond the scope of this paper)--leading into the Goldilocks algorithm solution. Goldilocks aims to simultaneously raise the selection likelihood floor (eliminating the 0% selection chance and improving representativeness), as well as lower the ceiling (eliminating the 100% selection case and making the process more robust against manipulation).

However, there is limited literature on what the outputs of these look like. Additionally, it appears that none of these directly address or validate the presence of any particular intersections within the panels they produce, which presents a risk for insufficient representation.

# Contribution

This study hopes to visualise the algorithm(s) used for sortition to demonstrate how they operate, the level of representation they achieve, and how they fall short when different issues are present in the data. There has been little done to showcase what these algorithms actually look like, which limits transparency and interpretability of the process.

Additionally, we hope to assess the difference in effectiveness and performance across different sample sizes, population distributions, and extreme cases, as real-world communities can be complex, and optimal sortition should be able to capture this confidently. Within this, we also hope to observe the nature of intersections captured by the algorithm.

[How do we make unobservables more interesting? Do we assign response rate to an unobservable? Would there be a way to do weighted response probabilities?]

## Methodology

As the main focus of this paper is visualising algorithmic performance, we will follow a simulation study method. The study will construct an example "population", from which a "survey sample" will be selected at random with different assumed response rates, at which point the sample will be passed through into the publicly accessible Panelot sortition interface (based on @Flanigan2021FairAF LexiMin) to run selection lottery, select a specific panel with a set seed for reproducibility, then pulled back for comparison against the distributions at previous steps.

## Expected results

As the algorithms are not defined to inspect presence of particular intersections, it is expected that there will be no way to ensure a certain "type" of person (beyond defined marginal categories) will be present within the selected panel.

## Small test case